In [1]:
import numpy as np

In [10]:
#create array of 6 random values in 0-100 range.
np.random.randint(1,100,6)

#reshape the array according to row and column vectors.
np.random.randint(1,100,6).reshape(3,2)

#create an array of uniform distribution (0,1)
np.random.rand(4)

#create a 3*3 identity matrix
np.eye(3)

#create a 3*3 identity matrix
np.zeros(3)

#create a 5*5 2-d array of zeros
np.zeros((5,5))

#return standard normal distribution vcenter around zreo.
np.random.randn(2,2)

# uninitialized
np.empty((2,3))

# from 0 to a number less than 2 with 0.3 intervals
np.arange(0, 2, 0.3)

# all element are 1
np.ones((2,3,4), dtype=np.int16)

# complex array
np.array([[1,2],[3,4]], dtype=complex) 

# two-dimensional array
np.array([(1.5,2,3),(4,5,6)])

# one-dimensional array
np.array([2,3,4])

array([2, 3, 4])

In [11]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A+B              #addition of two array
np.add(A,B)      #addition of two array
A * B            # elementwise product
A @ B            # matrix product
A.dot(B)         # another matrix product
B.T              #Transpose of B array
A.flatten()      #form 1-d array
B < 3            #Boolean of Matrix B. True for elements less than 3
A.sum()          # sum of all elements of A
A.sum(axis=0)    # sum of each column
A.sum(axis=1)    # sum of each row
A.cumsum(axis=1) # cumulative sum along each row
A.min()          # min value of all elements
A.max()          # max value of all elements
np.exp(B)        # exponential
np.sqrt(B)       # squre root
A.argmin()       #position of min value of elements 
A.argmax()       #position of max value of elements
A[1,1]           #member of a array in (1,1) position

1

Array Slicing

In [14]:
x = np.arange(10)
x


#from start to 4th position
x[:5]


#from 4th position to end
x[4:]


#from 4th to 6th position
x[4:7]


#return elements at even place
x[ : : 2]


#return elements from first position step by two
x[1::2]


#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
a = np.random.randint(1,100,35).reshape(5,7)
a

array([[25, 54, 14, 13, 51, 23, 89],
       [13, 71,  7, 24, 16, 93, 97],
       [78, 83, 61, 86, 28, 73, 19],
       [44, 62, 37, 71, 61, 75, 92],
       [20, 67, 16, 62, 70, 20, 35]])

In [8]:
a.T

array([[25, 13, 78, 44, 20],
       [54, 71, 83, 62, 67],
       [14,  7, 61, 37, 16],
       [13, 24, 86, 71, 62],
       [51, 16, 28, 61, 70],
       [23, 93, 73, 75, 20],
       [89, 97, 19, 92, 35]])

In [9]:
a.sum()

1750

In [10]:
a.sum(axis=0)

array([180, 337, 135, 256, 226, 284, 332])

In [11]:
a.sum(axis=1)

array([269, 321, 428, 442, 290])

In [13]:
b = np.random.randint(1,100,25).reshape(5,5)
b

array([[91, 72, 68, 81, 69],
       [77, 99, 77, 82, 32],
       [10, 13, 83, 20, 92],
       [94, 97, 63, 62, 74],
       [36, 95, 26, 70, 22]])

In [15]:
a*b
#tamanhos diferentes

ValueError: operands could not be broadcast together with shapes (5,7) (5,5) 